Bataille Navale Java/JavaFX: Bateau Class Reference
Bateau Class Reference
Classe permetant la création et l'initialisation des bateaux.
Public Member Functions
void initBateau (Case cases[][])
Fonction permettant d'initialiser les bateaux du jeu, et faisant appel à la fonction 'placerBateau' afin de les placer dans la grille passée en paramètre.
void placerBateau (Bateau b, Case cases[][])
Fonction qui permet de placer les bateaux sur le plateau de façon aléatoire.
boolean casesVides (Bateau b, Case c[][], int x, int y)
Fonction qui s'assure que le bateau soit placé dans des cases vides.
Static Public Member Functions
static int rand (int Min, int Max)
Fonction permettant d'obtenir un chiffre aléatoire.
Public Attributes
int taille
Taille du bateau (de 2 à 5 cases)
boolean etat
État du bateau : coulé/non coulé
int orientation
Bateau placé verticalement ou horizontalement.
Private Attributes
int vie
Vie du bateau.
Detailed Description
Classe permetant la création et l'initialisation des bateaux.
Definition at line 5 of file Bateau.java.
Member Function Documentation
casesVides()
boolean Bateau.casesVides (Bateau b, Case c[][], int x, int y)
Fonction qui s'assure que le bateau soit placé dans des cases vides.
Cette fonction vérifiera que les cases qui doivent potentiellement accueuillir le bateau soient libres. Elle renvera 'TRUE' si l'empacement est disponible, et 'FALSE' si il ne l'est pas
Definition at line 92 of file Bateau.java.
References orientation, and taille.
Referenced by placerBateau().
{
     int tb= b.taille;
     int j,z;
     if(b.orientation==1){//horizontal
         //tester les voisins de la premiere cases
         if(x > 0 && c[x-1][y].getState()==true) //haut
         return false;
         if(x < 10-1 && c[x+1][y].getState()==true) // bas
         return false;
         if(y > 0 && c[x][y-1].getState()==true) // droite
         return false;
         for( j = y ; j<(y+tb) ; j++){
         if(j>=10)
             return false;
         //voisin haut
         if(x-1 >= 0 && c[x-1][j].getState()==true)
             return false;
         //voisin bas
                 if (x+1 <= 10-1 && c[x+1][j].getState()==true)
             return false;
         if (c[x][j].getState()==true)
             return false;
         }
         //test de la derniere case
         j--;
         if(x > 0 && c[x-1][j].getState()==true) //haut
         return false;
         if(x < 10-1 && c[x+1][j].getState()==true) // bas
         return false;
         if(j < 10-1 && c[x][j+1].getState()==true) // droite
         return false;
     }
         else if(b.orientation==2){//vertical
         //test de la premiere case
         if(x-1 >= 0 && c[x-1][y].getState()==true) // haut
         return false;
         if(y < 10-1 && c[x][y+1].getState()==true) // droite
         return false;
         if(y > 0 && c[x][y-1].getState()==true) // gauche
         return false;
         for( z = x ; z<(x+tb) ; z++){
         if(z>=10)
             return false;
         //voisin gauche
         if(y-1 >= 0 && c[z][y-1].getState()==true)
             return false;
         //voisin droite
                 if (y+1 <= 10-1 && c[z][y+1].getState()==true)
             return false;
                 if (c[z][y].getState()==true)
             return false;
         }
         //test de la derniere case
         z--;
         if(z+1 <= 10-1 && c[z+1][y].getState()==true) // bas
         return false;
         if(y < 10-1 && c[x][y+1].getState()==true) // droite
         return false;
         if(y > 0 && c[x][y-1].getState()==true) // gauche
         return false;
     }
         return true;
     }
initBateau()
void Bateau.initBateau (Case cases[][])
Fonction permettant d'initialiser les bateaux du jeu, et faisant appel à la fonction 'placerBateau' afin de les placer dans la grille passée en paramètre.
Definition at line 28 of file Bateau.java.
References placerBateau().
Referenced by Game.mode_joueur_solo(), Game.mode_joueur_vs_IA(), Game.mode_joueur_vs_joueur(), and Game.reset().
{
         Bateau b1=new Bateau(5);
         Bateau b2=new Bateau(4);
         Bateau b3=new Bateau(3);
         Bateau b4=new Bateau(3);
         Bateau b5=new Bateau(2);
         b1.placerBateau(b1,cases);
         b2.placerBateau(b2,cases);
         b3.placerBateau(b3,cases);
         b4.placerBateau(b4,cases);
         b5.placerBateau(b5,cases);
     }
placerBateau()
void Bateau.placerBateau (Bateau b, Case cases[][])
Fonction qui permet de placer les bateaux sur le plateau de façon aléatoire.
Les coordonnées du bateau et son orientation seront obtenus en utilisant la fonction rand, puis, si l'espace que le bateau doit occupper est vide, il sera placé, sinon d'autres coordonnées seront généré jusqu'à ce que l'on obtienne un emplacement vide
Definition at line 53 of file Bateau.java.
References casesVides(), orientation, rand(), and taille.
Referenced by initBateau().
{
         int tb = b.taille;
         int ob = b.orientation;
         if (ob == 2) {
             int y;
             int x;
         x = rand(0,(10-tb)); //coordonnee horizontal
             y = rand(0,9); //coordonnee vertical
         if(casesVides(b, cases, x, y)==true){  //si case est vide
         for(int i = x ; i<(x+tb) ; i++)//initialise le bateau
             cases[i][y].setState(true);}//true=bateau present
         else {
         placerBateau(b, cases);
         }
     }
     else if(ob==1){ //bateau vertical
         int y;
             int x;
             x = rand(0,9); //coordonnee horizontal
             y = rand(0,(10-tb)); //coordonnee vertical
          if(casesVides(b, cases, x, y)){
          for(int i = y ; i< (y+tb) ; i++)//initialise le bateau
              cases[x][i].setState(true);}//la case change d'etat
          else{
          placerBateau(b, cases);
          }
     }
     }
rand()
static int Bateau.rand (int Min, int Max) static
Fonction permettant d'obtenir un chiffre aléatoire.
Il sera compris entre la valeur Min et la valeur Max, ou égal à l'une d'elles. Les valeures générées seront utilisées comme coordonnées pour les bateaux
Definition at line 45 of file Bateau.java.
Referenced by placerBateau().
{
         return (int)(Math.random() * (double)(Max - Min + 1)) + Min;
     }
Member Data Documentation
etat
boolean Bateau.etat
État du bateau : coulé/non coulé
Definition at line 11 of file Bateau.java.
orientation
int Bateau.orientation
Bateau placé verticalement ou horizontalement.
Definition at line 13 of file Bateau.java.
Referenced by casesVides(), and placerBateau().
taille
int Bateau.taille
Taille du bateau (de 2 à 5 cases)
Definition at line 7 of file Bateau.java.
Referenced by casesVides(), and placerBateau().
vie
int Bateau.vie private
Vie du bateau.
Definition at line 9 of file Bateau.java.
The documentation for this class was generated from the following file:
/Users/vijayakulanathanthanushan/Programmation/Java/Bataille navale/src/Bateau.java