Bataille Navale Java/JavaFX: IA Class Reference
IA Class Reference
Classe implémentant une intelligence artificielle, ainsi que sa façon de jouer.
Public Member Functions
IA ()
Constructeur de la classe IA, qui initialise la grille de l'IA.
void print_adversary_boat ()
Fonction qui affiche les bato adverse sur la grille de l'IA Nos bateaux étant placé sur la grille de l'IA, cette fonction sert à les rendres visible.
int random (int min, int max)
Fonction qui renvoie une valeur aléatoire comprise entre min inclu et max exclu.
void play ()
Fonction principale de la classe IA : La fonction va en premier temp choisir une case aléatoire parmis toutes les cases de la grille disponible, si elle tombe sur une case vide elle passe son tour, si elle tombe sur un bateau, alors elle enregistre sa position, continue à jouer, et passe à l'éxamen des cases voisines afin de compléter le bateau en question.
boolean shot_with_neighbor ()
Fonction permettant d'éxaminer les cases voisines si une case seule d'un bateau a été trouvée, (c'est à dire sans autre batteau dans le voisinage).
void random_shot ()
Fonction jouant une case aléatoire parmis toutes les cases disponible de la grille.
boolean continue_with_same_boat ()
Fonction permettant à l'IA de finir un bateau qu'elle aurait découvert : si deux bateaux ont été trouvés sur la meme lignée, alors la fonction par dans un sens de cette lignée afin de compléter le bateau.
Public Attributes
Grille grille
Variable de type 'Grille' pour la grille de l'IA.
int random_shootI
Variables acceuilant les coordonnées aléatoires en absicce de l'IA.
int random_shootJ
Variables acceuilant les coordonnées aléatoires en ordonnée de l'IA.
boolean touched_boat
Variable servant à savoir si l'IA a ou non touché un bateau, ceci déterminera sa façon de jouer par la suite.
int [][] record_place_of_boat
Tableau enrengistrant les coordonnées d'un bateau si il a été trouvé
boolean sens_opposé = false
Variable permettant d'éfféctuer une analyse dans le sens de la lignée des bateaux trouvés si la valeur de celle-ci est à 1.
int other_sens = 0
Variable permettant d'éfféctuer une analyse dans le sens opposé du sens de la lignée précédente.
boolean finish_the_boat = false
Variable permettant de savoir si oui ou non nous l'IA est dans une procédure de finition d'un bateau déja endomagé
Detailed Description
Classe implémentant une intelligence artificielle, ainsi que sa façon de jouer.
Definition at line 23 of file IA.java.
Constructor & Destructor Documentation
IA()
IA.IA ()
Constructeur de la classe IA, qui initialise la grille de l'IA.
Definition at line 43 of file IA.java.
References grille, and record_place_of_boat.
     {
         grille = new Grille(570,90, false);
         record_place_of_boat = new int[1][2];
     }
Member Function Documentation
continue_with_same_boat()
boolean IA.continue_with_same_boat ()
Fonction permettant à l'IA de finir un bateau qu'elle aurait découvert : si deux bateaux ont été trouvés sur la meme lignée, alors la fonction par dans un sens de cette lignée afin de compléter le bateau.
Si l'IA est bloqué lors de ce premier passage, par une case vide par exemple, ou le bord de la grille, alors la variable 'other_sens' est initialisé à 'TRUE' afin de repartir dans le sens opposé, et l'IA complète donc le bateau en question en repartant dans le sens opposé.
Une fois la procédure terminée, la fonction 'play' se charge de réinitialisé la variable touched_boat à 'false' afin que l'IA reprenne ses coups aléatoires.
Definition at line 206 of file IA.java.
References Case.boat, Grille.cases, finish_the_boat, Grille.grilleH, other_sens, random_shootI, random_shootJ, random_shot(), sens_opposé, and Case.visited.
Referenced by play().
     {
         boolean neighbor_boat = false;
         int x = this.record_place_of_boat[0][0]; // position I du bato trouvé
         int y = this.record_place_of_boat[0][1]; // position J du bato trouvé
         int j;
         //si un voisin est un bato
         if(sens_opposé == false)
         {
                 //---en haut-----------------------------------------------------------------
                 if(x-1 >= 0 && this.grille.cases[x-1][y].boat == true && this.grille.cases[x-1][y].visited == true)
                 {
                     j=x;
                     while(j-1 >= 0 )
                     {
                         if(this.grille.cases[j-1][y].visited == false)
{
                             random_shootI = j-1;
                             random_shootJ = y;
                             System.out.println("HAUT");
                             other_sens = 1;
                             finish_the_boat = true;
                             return true;
                         }
                         if(j-1 < 0 || this.grille.cases[j-1][y].visited == true && this.grille.cases[j-1][y].boat == false)
{
                             sens_opposé = true;
                             other_sens = 1;
                             break;
                         }/*
                         if(this.grille.cases[j-1][y].visited == true && this.grille.cases[j-1][y].boat == true)
{
                             other_sens = 1;
                             finish_the_boat = true;
                         }*/
                         j--;
                     }
                 }
                 //---en bas-----------------------------------------------------------------
                 if(x+1 <= Grille.grilleH-1 && this.grille.cases[x+1][y].boat == true && this.grille.cases[x+1][y].visited == true)
                 {
                     j=x;
                     while(j+1 <= Grille.grilleH-1 )
                     {
                         if(this.grille.cases[j+1][y].visited == false)
{
                             random_shootI = j+1;
                             random_shootJ = y;
                             System.out.println("BAS");
                             other_sens = 2;
                             finish_the_boat = true;
                             return true;
                         }
                         if( j+1 >= Grille.grilleH || this.grille.cases[j+1][y].visited == true && this.grille.cases[j+1][y].boat == false)
{
                             sens_opposé = true;
                             other_sens = 2;
                             break;
                         }/*
                         if(this.grille.cases[j+1][y].visited == true && this.grille.cases[j+1][y].boat == true)
{
                             sens_opposé = true;
                             other_sens = 2;
                             finish_the_boat = true;
                         }*/
                         j++;
                     }
                 }
                 //---a gauche----------------------------------------------------------------
                 if(y-1 >= 0 && this.grille.cases[x][y-1].boat == true && this.grille.cases[x][y-1].visited == true)
                 {
                     j=y;
                     while(j-1 >= 0 )
                     {
                         if(this.grille.cases[x][j-1].visited == false)
{
                             random_shootI = x;
                             random_shootJ = j-1;
                             System.out.println(" GAUCHE");
                             other_sens = 3;
                             finish_the_boat = true;
                             return true;
                         }
                         if( j-1 < 0 || this.grille.cases[x][j-1].visited == true && this.grille.cases[x][j-1].boat == false)
{
                             sens_opposé = true;
                             other_sens = 3;
                             break;
                         }/*
                         if(this.grille.cases[x][j-1].visited == true && this.grille.cases[x][j-1].boat == true)
{
                             sens_opposé = true;
                             other_sens = 3;
                             finish_the_boat = true;
                         }*/
                         j--;
                     }
                 }
                 //----a droite---------------------------------------------------------------
                 if(y+1 <= Grille.grilleW-1 && this.grille.cases[x][y+1].boat == true && this.grille.cases[x][y+1].visited == true)
                 {
                     j=y;
                     while(j+1 <= Grille.grilleW-1 )
                     {
                         if(this.grille.cases[x][j+1].visited == false)
{
                             random_shootI = x;
                             random_shootJ = j+1;
                             System.out.println("DROITE");
                             other_sens = 4;
                             finish_the_boat = true;
                             return true;
                         }
                         if(j+1 >= Grille.grilleW || this.grille.cases[x][j+1].visited == true && this.grille.cases[x][j+1].boat == false)
{
                             sens_opposé = true;
                             other_sens = 4;
                             break;
                         }/*
                         if(this.grille.cases[x][j+1].visited == true && this.grille.cases[x][j+1].boat == true)
{
                             sens_opposé = true;
                             other_sens = 4;
                             finish_the_boat = true;
                         }*/
                         j++;
                     }
                 }
         }
         System.out.println("opposé = "+ other_sens);
         //-------------------------------------------------------------------------------
         //en bas
         if(sens_opposé == true)
         {
                 if(other_sens == 1)
                 {
                     j=x;
                     while(j+1 <= Grille.grilleH-1 )
                     {
                         if(this.grille.cases[j+1][y].visited == false)
{
                             random_shootI = j+1;
                             random_shootJ = y;
                             System.out.println("opposé BAS");
                             return true;
                         }
                         if(j+1 >= Grille.grilleH || (this.grille.cases[j+1][y].visited == true && this.grille.cases[j+1][y].boat == false))
{
                             this.touched_boat = false; // optionnel
                             this.finish_the_boat = false;
                             this.other_sens = 0;
                             this.sens_opposé = false;
                             random_shot();
                             return true;
                         }
                         j++;
                     }
                 }
                 //------------------------------------------------------------------------------
                 // en haut
                 if(other_sens == 2)
                 {
                     j=x;
                     while(j-1 >= 0)
                     {
                         if(this.grille.cases[j-1][y].visited == false)
{
                             random_shootI = j-1;
                             random_shootJ = y;
                             System.out.println("opposé HAUT");
                             return true;
                         }
                         if(j-1 < 0 || (this.grille.cases[j-1][y].visited == true && this.grille.cases[j-1][y].boat == false))
{
                             this.touched_boat = false;
                             this.finish_the_boat = false;
                             this.other_sens = 0;
                             this.sens_opposé = false;
                             random_shot();
                             return true;
                         }
                         j--;
                     }
                 }
                 //----------------------------------------------------------------------------------
                 if(other_sens == 3)
                 {
                     j=y;
                      while(j+1 <= Grille.grilleW-1 )
                     {
                         if(this.grille.cases[x][j+1].visited == false)
{
                             random_shootI = x;
                             random_shootJ = j+1;
                             System.out.println("opposé GAUCHE");
                             return true;
                         }
                          if(j+1 >= Grille.grilleW || (this.grille.cases[x][j+1].visited == true && this.grille.cases[x][j+1].boat == false))
{
                             this.touched_boat = false;
                             this.finish_the_boat = false;
                             this.other_sens = 0;
                             this.sens_opposé = false;
                             random_shot();
                             return true;
                         }
                         j++;
                     }
                 }
                 //---------------------------------------------------------------------------------
                 if(other_sens == 4)
                 {
                     j=y;
                     while(j-1 >= 0 )
                     {
                         if(this.grille.cases[x][j-1].visited == false)
{
                             random_shootI = x;
                             random_shootJ = j-1;
                             System.out.println("opposé DROITE");
                             return true;
                         }
                         if(j-1 < 0 || (this.grille.cases[x][j-1].visited == true && this.grille.cases[x][j-1].boat == false))
{
                             this.touched_boat = false;
                             this.finish_the_boat = false;
                             this.other_sens = 0;
                             this.sens_opposé = false;
                             random_shot();
                             return true;
                         }
                         j--;
                     }
                 }
         }
          if(finish_the_boat == true)
                 sens_opposé = true;
        return false;
     }
play()
void IA.play ()
Fonction principale de la classe IA : La fonction va en premier temp choisir une case aléatoire parmis toutes les cases de la grille disponible, si elle tombe sur une case vide elle passe son tour, si elle tombe sur un bateau, alors elle enregistre sa position, continue à jouer, et passe à l'éxamen des cases voisines afin de compléter le bateau en question.
Definition at line 77 of file IA.java.
References Case.boat, Grille.cases, continue_with_same_boat(), finish_the_boat, Case.forme, random_shootI, random_shootJ, random_shot(), Grille.score, sens_opposé, shot_with_neighbor(), Grille.test_win_or_loose(), and Case.visited.
Referenced by Case.Case().
     {
         //si coup précédent était un bato alors le prochain coup sera plus réfléchi
          if(this.touched_boat == true)
         {
             if(!continue_with_same_boat())
             {
                 if(!shot_with_neighbor())
                     random_shot();
             }
         }
         //si au coup précédent pas de bato touché, alors l'IA tape un coup aléatoire
         else
          {
              System.out.println("RANDOM");
              random_shot();
          }
         //Analyse du coup joué
         if(this.grille.cases[random_shootI][random_shootJ].boat == true)
         {
             this.grille.cases[random_shootI][random_shootJ].visited = true;
             this.grille.cases[random_shootI][random_shootJ].forme.setFill(Color.RED);
             this.touched_boat = true;
             this.grille.score();
             //si le coup tapé est un bato et que nous somme pas déja dans une procédure de finition de bato, alors on enregistre le bato en question
             if(finish_the_boat != true)
             {
                 this.record_place_of_boat[0][0] = random_shootI;
                 this.record_place_of_boat[0][1] = random_shootJ;
             }
             this.grille.test_win_or_loose();
             // Timeline pour retarder le coup de l'IA d'une seconde et rappeler la fonction play car un bato a été trouvé et l'IA garde la main au prochain tour
             Timeline pause = new Timeline(
                                     new KeyFrame(
                                       Duration.millis(1000),
                                       actionEvent -> play()
                                     )
                                 );
                                 pause.play();
         }
         //si on tombe sur une case vide, alors on affiche une croix, et on modifie les valeurs des variables de la case
         else
         {
             if(finish_the_boat == true)
                 sens_opposé = true;
             this.grille.cases[random_shootI][random_shootJ].visited = true;
             this.grille.cases[random_shootI][random_shootJ].forme.setFill(Color.CORNFLOWERBLUE);
             this.grille.test_win_or_loose();
         }
     }
print_adversary_boat()
void IA.print_adversary_boat ()
Fonction qui affiche les bato adverse sur la grille de l'IA Nos bateaux étant placé sur la grille de l'IA, cette fonction sert à les rendres visible.
Definition at line 52 of file IA.java.
References Case.boat, Grille.cases, Case.forme, and Grille.grilleH.
Referenced by Game.mode_joueur_vs_IA().
     {
         for (int i = 0; i < this.grille.grilleH; i++)
         {
             for (int j = 0; j < this.grille.grilleW; j++)
             {
                 if(this.grille.cases[i][j].boat == true)
                     this.grille.cases[i][j].forme.setFill(Color.GREY);
             }
         }
     }
random()
int IA.random (int min, int max)
Fonction qui renvoie une valeur aléatoire comprise entre min inclu et max exclu.
Cette fonction sera utilisé dans le cadre du coup alétoire pour l'IA.
Definition at line 67 of file IA.java.
Referenced by random_shot(), and shot_with_neighbor().
     {
         return (int)(Math.random() * (max - min)) + min;
     }
random_shot()
void IA.random_shot ()
Fonction jouant une case aléatoire parmis toutes les cases disponible de la grille.
Definition at line 185 of file IA.java.
References Grille.cases, Grille.grilleH, other_sens, random(), random_shootI, random_shootJ, sens_opposé, and Case.visited.
Referenced by continue_with_same_boat(), and play().
     {
         do
             {
                 this.random_shootI = random(0,this.grille.grilleH);
                 this.random_shootJ = random(0,this.grille.grilleW);
             }while(this.grille.cases[random_shootI][random_shootJ].visited == true);
     sens_opposé = false;
     other_sens = 0;
     }
shot_with_neighbor()
boolean IA.shot_with_neighbor ()
Fonction permettant d'éxaminer les cases voisines si une case seule d'un bateau a été trouvée, (c'est à dire sans autre batteau dans le voisinage).
La fonction analyse donc les cases jouables dans le voisinage du batteau trouvée, et choisie une case aléatoirement parmis celle-ci
Definition at line 138 of file IA.java.
References Grille.cases, Grille.grilleH, random(), random_shootI, random_shootJ, and Case.visited.
Referenced by play().
     {
             int number_possibilities = 0; // variable pour le nombre de possibilité alentours
             int[][] next_possibilities = new int[4][2]; //tablo ki enregistre les voisins ou on peut cliker
             int x = this.record_place_of_boat[0][0]; // position I du bato trouvé
             int y = this.record_place_of_boat[0][1]; // position J du bato trouvé
             int rand_possibilities;
            //premiere étape est de tester si il y a des cases de dispo sur les côté
             if(x-1 >= 0 && this.grille.cases[x-1][y].visited == false)
             {
                 number_possibilities ++;
                 next_possibilities[number_possibilities-1][0] = x-1;
                 next_possibilities[number_possibilities-1][1] = y;
             }
             if(x+1 <= Grille.grilleH-1 && this.grille.cases[x+1][y].visited == false)
             {
                 number_possibilities ++;
                 next_possibilities[number_possibilities-1][0] = x+1;
                 next_possibilities[number_possibilities-1][1] = y;
             }
             if(y-1 >= 0 && this.grille.cases[x][y-1].visited == false)
             {
                 number_possibilities ++;
                 next_possibilities[number_possibilities-1][0] = x;
                 next_possibilities[number_possibilities-1][1] = y-1;
             }
             if(y+1 <= Grille.grilleW-1 && this.grille.cases[x][y+1].visited == false)
             {
                 number_possibilities ++;
                 next_possibilities[number_possibilities-1][0] = x;
                 next_possibilities[number_possibilities-1][1] = y+1;
             }
             //si on a des case disponible a coté alors on en choisi une parmis elle aléatoirement
             if(number_possibilities != 0)
             {
                 rand_possibilities = random(0, number_possibilities);
                 random_shootI = next_possibilities[rand_possibilities][0];
                 random_shootJ = next_possibilities[rand_possibilities][1];
                 System.out.println("NEIGHBBOR RANDOM ");
                 return true;
             }
          return false;
     }
Member Data Documentation
finish_the_boat
boolean IA.finish_the_boat = false
Variable permettant de savoir si oui ou non nous l'IA est dans une procédure de finition d'un bateau déja endomagé
Definition at line 40 of file IA.java.
Referenced by continue_with_same_boat(), and play().
grille
Grille IA.grille
Variable de type 'Grille' pour la grille de l'IA.
Definition at line 26 of file IA.java.
Referenced by IA(), and Game.mode_joueur_vs_IA().
other_sens
int IA.other_sens = 0
Variable permettant d'éfféctuer une analyse dans le sens opposé du sens de la lignée précédente.
Definition at line 38 of file IA.java.
Referenced by continue_with_same_boat(), and random_shot().
random_shootI
int IA.random_shootI
Variables acceuilant les coordonnées aléatoires en absicce de l'IA.
Definition at line 28 of file IA.java.
Referenced by continue_with_same_boat(), play(), random_shot(), and shot_with_neighbor().
random_shootJ
int IA.random_shootJ
Variables acceuilant les coordonnées aléatoires en ordonnée de l'IA.
Definition at line 30 of file IA.java.
Referenced by continue_with_same_boat(), play(), random_shot(), and shot_with_neighbor().
record_place_of_boat
int [][] IA.record_place_of_boat
Tableau enrengistrant les coordonnées d'un bateau si il a été trouvé
Definition at line 34 of file IA.java.
Referenced by IA().
sens_opposé
boolean IA.sens_opposé = false
Variable permettant d'éfféctuer une analyse dans le sens de la lignée des bateaux trouvés si la valeur de celle-ci est à 1.
Definition at line 36 of file IA.java.
Referenced by continue_with_same_boat(), play(), and random_shot().
touched_boat
boolean IA.touched_boat
Variable servant à savoir si l'IA a ou non touché un bateau, ceci déterminera sa façon de jouer par la suite.
Definition at line 32 of file IA.java.
The documentation for this class was generated from the following file:
/Users/vijayakulanathanthanushan/Programmation/Java/Bataille navale/src/IA.java