Bataille Navale Java/JavaFX: Game Class Reference
Game Class Reference
Classe principale du programme, regroupant les différents mode de jeu ainsi que les variables principales du programme.
Classes
enum Mode
Enumeration listant les différents mode de jeu.
Public Member Functions
Game (Stage jeu)
Constructeur de la classe Game : ce constructeur initialise l'ensemble les différentes scènes des différents mode de jeu du programme.
void difficulty_screen (Stage jeu)
Fonction qui affiche les trois bouton de difficulté lorsque l'on accède au mode solo, et initialise le nombre de coup de départ dans l'attribut 'int coup_depart'.
void mode_joueur_solo (Stage jeu)
Fonction initialisant le mode solo en fonction de la difficultée choisie.
void mode_joueur_vs_joueur (Stage jeu)
Fonction initialisant le mode joueur contre joueur : Ce mode permet a deux joueurs humains de s'affronter.
void mode_joueur_vs_IA (Stage jeu)
Fonction initialisant le mode joueur contre IA : Ce mode permet au joueur de jouer contre l'ordinateur.
void reset (Grille grille, Group group)
Fonction reset qui réinitialise la grille dans son 'group' correspondant passé en paramètres.
Public Attributes
Scene parti_vs_IA
Les scenes pour chaque fenetre.
Static Public Attributes
static Group groupe_solo
Les groupes pour chaque fenetre.
static Mode mode_de_jeu
Variable de type enumeration.
static IA ia
Variable de l'IA.
static Grille joueur_solo
Création des grilles pour chaqe mode : 5 grille au total pour tous le programme.
static int coup_restant
Variable contenant le nombre de coup_restant pour le mode solo.
static int coup_depart
Variable contenant le nombre de coup de d"part en fonction de la difficultée choisie pour le mode solo.
static Text text_coup_restant
Variable de type 'Text' pour afficher le nombre de coup restant dans le mode solo.
Detailed Description
Classe principale du programme, regroupant les différents mode de jeu ainsi que les variables principales du programme.
Definition at line 60 of file Game.java.
Constructor & Destructor Documentation
Game()
Game.Game (Stage jeu)
Constructeur de la classe Game : ce constructeur initialise l'ensemble les différentes scènes des différents mode de jeu du programme.
Definition at line 83 of file Game.java.
References coup_restant, groupe_solo, parti_vs_IA, and text_coup_restant.
     {
         //Initialisation des variables principale pour le jeu
         text_coup_restant = new Text(); // texte affichant le nombre de coup restant pour le mode solo
         coup_restant = 0; // variable stockant le nombre de coup restant pour le mode solo
         groupe_joueur_vs_IA = new Group(); // group pour le mode joueur contre IA
         groupe_solo = new Group(); // group pour le mode solo
         difficulty_group_solo = new Group(); // group affichant les boutons de difficultée pour le mode solo
         groupe_joueur_vs_joueur = new Group();// group pour le mode joueur contre joueur
         difficulty_screen = new Scene(difficulty_group_solo, 1024, 597, Color.WHITE); //scene pour les choix de difficulté du mode solo
         parti_vs_IA = new Scene(groupe_joueur_vs_IA, 1024, 597, Color.WHITE);  // scene pour le mode joueur contre IA
         parti_vs_joueur = new Scene(groupe_joueur_vs_joueur, 1024, 597, Color.WHITE);  // scene pour le mode joueur contre joueur
         parti_solo = new Scene(groupe_solo, 1024, 597, Color.WHITE);  // scene pour le mode solo
     }
Member Function Documentation
difficulty_screen()
void Game.difficulty_screen (Stage jeu)
Fonction qui affiche les trois bouton de difficulté lorsque l'on accède au mode solo, et initialise le nombre de coup de départ dans l'attribut 'int coup_depart'.
"Facile" = 80 coups
"Moyen" = 50 coups
"Difficile" = 30 coups
Definition at line 106 of file Game.java.
References Acceuil.Accueil, coup_depart, and coup_restant.
     {
         Text text = new Text();
         ImageView fond_jeu = new ImageView(new Image(getClass().getResource("images/jeu.jpeg").toExternalForm()));
         HBox difficulty_button = new HBox(); //creation d'une VBox pour alinger les boutonsVbox
         difficulty_button.setSpacing(80);//espace entre boutonsVbox
         difficulty_button.setTranslateX(325); // position de la Vbox
         difficulty_button.setTranslateY(270);
         text.setFont(Font.font("Brushed script", FontWeight.BOLD, 35));
         text.setFill(Color.WHITE);
         text.setX(difficulty_button.getTranslateX() );
         text.setY(difficulty_button.getTranslateY()-70);
         text.setOpacity(0.8);
         text.setText("Choisissez la difficultée");
         //on créé les boutons difficultée, si on clik sur un bouton on initialise les variables a une certaine difficultée
                 Button facile = new Button("Facile");
                 facile.setOnMouseClicked(new EventHandler<MouseEvent>(){
                     @Override
                     public void handle(MouseEvent e)
                     {
                         coup_depart = 80;
                         coup_restant = 80;
                         afficher_coup_restant();
                         jeu.setScene(parti_solo);
                     }
                 });
                 facile.setMaxWidth(100); //definition de la taille du bouton
                 facile.setFont(Font.font("Cambria", 17));
                 facile.setOpacity(0.8);
                 Button moyen = new Button("Moyen");
                 moyen.setOnMouseClicked(new EventHandler<MouseEvent>(){
                     @Override
                     public void handle(MouseEvent e)
                     {
                         coup_depart = 50;
                         coup_restant = 50;
                         afficher_coup_restant();
                         jeu.setScene(parti_solo);
                     }
                 });
                 moyen.setMaxWidth(100); //definition de la taille du bouton
                 moyen.setFont(Font.font("Cambria", 17));
                 moyen.setOpacity(0.8);
                 Button difficile = new Button("Difficile");
                 difficile.setOnMouseClicked(new EventHandler<MouseEvent>(){
                     @Override
                     public void handle(MouseEvent e)
                     {
                         coup_depart = 30;
                         coup_restant = 30;
                         afficher_coup_restant();
                         jeu.setScene(parti_solo);
                     }
                 });
                 difficile.setMaxWidth(100); //definition de la taille du bouton
                 difficile.setFont(Font.font("Cambria", 17));
                 difficile.setOpacity(0.8);
                 Button retour = new Button("Retour");
                 retour.setOnMouseClicked(new EventHandler<MouseEvent>(){
                     @Override
                     public void handle(MouseEvent e)
                     {
                         jeu.setScene(Acceuil.Accueil);
                     }
                 });
                 retour.setMaxWidth(100); //definition de la taille du bouton
                 retour.setFont(Font.font("Cambria", 17));
                 retour.setTranslateX(474);
                 retour.setTranslateY(400);
                 retour.setOpacity(0.8);
         difficulty_group_solo.getChildren().add(fond_jeu);
         difficulty_group_solo.getChildren().add(text);
         difficulty_group_solo.getChildren().add(retour);
         difficulty_button.getChildren().addAll(facile, moyen, difficile);
         difficulty_group_solo.getChildren().add(difficulty_button);
     }
mode_joueur_solo()
void Game.mode_joueur_solo (Stage jeu)
Fonction initialisant le mode solo en fonction de la difficultée choisie.
Dans ce mode, le joueur possède une grille, et doit trouver l'intégralité des bateaux cachés (Les bateaux sont placés aléatoirements) avec un nombre de coup définit par la difficultée choisie au départ. Le joueur a la possibilité de réinitialisé le mode.
Definition at line 195 of file Game.java.
References Grille.cases, groupe_solo, Bateau.initBateau(), joueur_solo, parti_vs_IA, reset(), and text_coup_restant.
Referenced by Acceuil.Acceuil().
     {
         joueur_solo = new Grille(200,90,true);
         ImageView fond_jeu = new ImageView(new Image(getClass().getResource("images/jeu.jpeg").toExternalForm()));
         Bateau bateau = new Bateau(0);
         bateau.initBateau(joueur_solo.cases);
         //bouton reset pour réinitialisé la grille du joueur et le compteur
         Button reset = new Button("Reset");
         reset.setOnMouseClicked(new EventHandler<MouseEvent>(){
             @Override
             public void handle(MouseEvent e)
             {
                 reset(joueur_solo, groupe_solo);
             }
         });
         reset.setMaxWidth(100); //definition de la taille du bouton
         reset.setTranslateX((parti_vs_IA.getWidth()/2) - 136);
         reset.setTranslateY(10);
         reset.setFont(Font.font("Cambria", 17));
         reset.setOpacity(0.8);
         //boutons retour pour revenir à l'acceuil a partir des parties
         Button retour = new Button("Retour");
         retour.setOnMouseClicked(new EventHandler<MouseEvent>(){
             @Override
             public void handle(MouseEvent e)
             {
                 reset(joueur_solo, null);
                 jeu.setScene(difficulty_screen);
             }
         });
         retour.setMaxWidth(100); //definition de la taille du bouton
         retour.setTranslateX((parti_vs_IA.getWidth()/2) - 140);
         retour.setTranslateY(50);
         retour.setFont(Font.font("Cambria", 17));
         retour.setOpacity(0.8);
         groupe_solo.getChildren().add(fond_jeu);
         groupe_solo.getChildren().add(joueur_solo);
         groupe_solo.getChildren().add(reset);
         groupe_solo.getChildren().add(retour);
         groupe_solo.getChildren().add(text_coup_restant);
     }
mode_joueur_vs_IA()
void Game.mode_joueur_vs_IA (Stage jeu)
Fonction initialisant le mode joueur contre IA : Ce mode permet au joueur de jouer contre l'ordinateur.
(Les bateaux sont placés aléatoirements). Le joueur et l'IA possédant chacun leur grille, le but sera tous comme le mode joueur cotre joueur, de coulé l'intégralité des bateaux de l'adversaires avant que celui-ci ne coule les notres. Le joueur a la possibilité de réinitialisé la partie.
Definition at line 330 of file Game.java.
References Acceuil.Accueil, Grille.cases, IA.grille, ia, Bateau.initBateau(), parti_vs_IA, IA.print_adversary_boat(), and reset().
Referenced by Acceuil.Acceuil().
     {
         Text nameText = new Text();
         ImageView fond_jeu = new ImageView(new Image(getClass().getResource("images/jeu.jpeg").toExternalForm()));
         joueur_mode_IA = new Grille(35,90,true);
         ia = new IA();
         Bateau bateau = new Bateau(0);
         bateau.initBateau(joueur_mode_IA.cases);
         bateau.initBateau(ia.grille.cases);
         ia.print_adversary_boat();
         Button reset = new Button("Reset");
         reset.setOnMouseClicked(new EventHandler<MouseEvent>(){
             @Override
             public void handle(MouseEvent e)
             {
                 reset(joueur_mode_IA, groupe_joueur_vs_IA);
                 reset(ia.grille, groupe_joueur_vs_IA);
                 ia.print_adversary_boat();
             }
         });
         reset.setMaxWidth(100); //definition de la taille du bouton
         reset.setTranslateX((parti_vs_IA.getWidth()/2) - 36);
         reset.setTranslateY(10);
         reset.setFont(Font.font("Cambria", 17));
         reset.setOpacity(0.8);
         //boutons retour pour revenir à l'acceuil a partir des parties
         Button retour = new Button("Retour");
         retour.setOnMouseClicked(new EventHandler<MouseEvent>(){
             @Override
             public void handle(MouseEvent e)
             {
                 reset(joueur_mode_IA, null);
                 reset(ia.grille, null);
                 ia.print_adversary_boat();
                 jeu.setScene(Acceuil.Accueil);
             }
         });
         retour.setMaxWidth(100); //definition de la taille du bouton
         retour.setTranslateX((parti_vs_IA.getWidth()/2) - 40);
         retour.setTranslateY(50);
         retour.setFont(Font.font("Cambria", 17));
         retour.setOpacity(0.8);
         nameText.setFont(Font.font("Brushed script", FontWeight.BOLD, 35));
         nameText.setFill(Color.WHITE);
         nameText.setX(185);
         nameText.setY(50);
         nameText.setOpacity(0.8);
     nameText.setStroke(Color.BLACK);
         nameText.setText("JOUEUR\t\t\t\tANDROID ");
         groupe_joueur_vs_IA.getChildren().add(fond_jeu);
         groupe_joueur_vs_IA.getChildren().add(ia.grille);
         groupe_joueur_vs_IA.getChildren().add(joueur_mode_IA);
         groupe_joueur_vs_IA.getChildren().add(retour);
         groupe_joueur_vs_IA.getChildren().add(nameText);
         groupe_joueur_vs_IA.getChildren().add(reset);
     }
mode_joueur_vs_joueur()
void Game.mode_joueur_vs_joueur (Stage jeu)
Fonction initialisant le mode joueur contre joueur : Ce mode permet a deux joueurs humains de s'affronter.
Chacun des joueurs possédant une grille, (Les bateaux sont placés aléatoirements), le but du jeu est de trouvé l'intégralité des bateaux de l'adversaire avant que celui-ci ne coule tous les notres. Les joueurs ont la possibilitées de réinitialisées la partie.
Definition at line 263 of file Game.java.
References Acceuil.Accueil, Grille.cases, Bateau.initBateau(), parti_vs_IA, and reset().
Referenced by Acceuil.Acceuil().
     {
         Text nameText = new Text();
         joueur1 = new Grille(35,90,true);
         joueur2 = new Grille(570,90,true);
         ImageView fond_jeu = new ImageView(new Image(getClass().getResource("images/jeu.jpeg").toExternalForm()));
         Bateau bateau = new Bateau(0);
         bateau.initBateau(joueur1.cases);
         bateau.initBateau(joueur2.cases);
         Button reset = new Button("Reset");
         reset.setOnMouseClicked(new EventHandler<MouseEvent>(){
             @Override
             public void handle(MouseEvent e)
             {
                 reset(joueur1, groupe_joueur_vs_joueur);
                 reset(joueur2, groupe_joueur_vs_joueur);
             }
         });
         reset.setMaxWidth(100); //definition de la taille du bouton
         reset.setTranslateX((parti_vs_IA.getWidth()/2) - 36);
         reset.setTranslateY(10);
         reset.setFont(Font.font("Cambria", 17));
         reset.setOpacity(0.8);
         //boutons retour pour revenir à l'acceuil a partir des parties
         Button retour = new Button("Retour");
         retour.setOnMouseClicked(new EventHandler<MouseEvent>(){
             @Override
             public void handle(MouseEvent e)
             {
                 reset(joueur1, null);
                 reset(joueur2, null);
                 jeu.setScene(Acceuil.Accueil);
             }
         });
         retour.setMaxWidth(100);
         retour.setTranslateX((parti_vs_IA.getWidth()/2) - 40);
         retour.setTranslateY(50);
         retour.setFont(Font.font("Cambria", 17));
         retour.setOpacity(0.8);
         nameText.setFont(Font.font("Brushed script", FontWeight.BOLD, 35));
         nameText.setFill(Color.WHITE);
         nameText.setX(35 + 150);
         nameText.setY(50);
         nameText.setOpacity(0.8);
     nameText.setStroke(Color.BLACK);
         nameText.setText("JOUEUR 1\t\t\t\t\tJOUEUR 2 ");
         groupe_joueur_vs_joueur.getChildren().add(fond_jeu);
         groupe_joueur_vs_joueur.getChildren().add(nameText);
         groupe_joueur_vs_joueur.getChildren().add(joueur2);
         groupe_joueur_vs_joueur.getChildren().add(joueur1);
         groupe_joueur_vs_joueur.getChildren().add(reset);
         groupe_joueur_vs_joueur.getChildren().add(retour);
     }
reset()
void Game.reset (Grille grille, Group group)
Fonction reset qui réinitialise la grille dans son 'group' correspondant passé en paramètres.
Cette fonction parcours l'intégralitée de la grille, et réinitialise chacun des champs de chaque case. Une fois la grille réinitialisée, une appel de la fonction 'initBateau' est éfféctué afin de replacer des bateaux aléatoirement
Definition at line 397 of file Game.java.
References Case.boat, Grille.cases, coup_depart, coup_restant, Case.forme, Grille.grilleH, Bateau.initBateau(), mode_de_jeu, Grille.score, Case.visited, and Grille.win_picture.
Referenced by mode_joueur_solo(), mode_joueur_vs_IA(), and mode_joueur_vs_joueur().
     {
         for(int i=0; i<grille.grilleH; i++)
         {
             for(int j=0; j< grille.grilleW; j++)
             {
                 if(grille.cases[i][j].boat == true || grille.cases[i][j].visited == true)
                 {
                     grille.cases[i][j].boat = false;
                     grille.cases[i][j].visited = false;
                     grille.cases[i][j].forme.setFill(Color.WHITE);
                 }
             }
         }
         Bateau bateau= new Bateau(0);
         bateau.initBateau(grille.cases);
         grille.score();
         Text reset_text = new Text();
         reset_text.setFont(Font.font("Brushed script", FontWeight.BOLD, 13));
         reset_text.setFill(Color.WHITE);
         reset_text.setX(5);
         reset_text.setY(14);
         reset_text.setOpacity(0.8);
         reset_text.setText("Grille Réinitialisée avec succès !");
         if(group != null)
         {
             Timeline print_reset = new Timeline(
                                 new KeyFrame(
                                   Duration.ZERO,
                                   actionEvent ->  group.getChildren().add(reset_text)
                                     ),
                                 new KeyFrame(
                                  Duration.millis(2000), actionEvent -> reset_text.setVisible(false))
                                 );
                                 print_reset.play();
         }
         //si le mode est solo, alors on doit aussi réinitialisé le nombre de coup restant et le remettre a sa valeur de départ
         if(mode_de_jeu == Mode.SOLO)
         {
             if(coup_depart == 80)
                 coup_restant = 80;
             if(coup_depart == 50)
                 coup_restant = 50;
             if(coup_depart == 30)
                 coup_restant = 30;
             afficher_coup_restant();
         }
         //Ceci sert à retirer les images win et game_over lorsque l'on a gagné ou perdu et que l'on clique sur reset pour recommencer
         if(grille.win_picture != null)
             grille.win_picture.setVisible(false);
         if(grille.game_over_picture != null)
             grille.game_over_picture.setVisible(false);
     }
Member Data Documentation
coup_depart
int Game.coup_depart static
Variable contenant le nombre de coup de d"part en fonction de la difficultée choisie pour le mode solo.
Definition at line 77 of file Game.java.
Referenced by difficulty_screen(), reset(), and Grille.test_win_or_loose().
coup_restant
int Game.coup_restant static
Variable contenant le nombre de coup_restant pour le mode solo.
Definition at line 75 of file Game.java.
Referenced by Case.Case(), difficulty_screen(), Game(), reset(), and Grille.test_win_or_loose().
groupe_solo
Group Game.groupe_solo static
Les groupes pour chaque fenetre.
Definition at line 65 of file Game.java.
Referenced by Game(), and mode_joueur_solo().
ia
IA Game.ia static
Variable de l'IA.
Definition at line 71 of file Game.java.
Referenced by Case.Case(), and mode_joueur_vs_IA().
joueur_solo
Grille Game.joueur_solo static
Création des grilles pour chaqe mode : 5 grille au total pour tous le programme.
Definition at line 73 of file Game.java.
Referenced by Case.Case(), and mode_joueur_solo().
mode_de_jeu
Mode Game.mode_de_jeu static
Variable de type enumeration.
Definition at line 67 of file Game.java.
Referenced by Acceuil.Acceuil(), Case.Case(), Grille.print_game_over(), Grille.print_win(), reset(), and Grille.test_win_or_loose().
parti_vs_IA
Scene Game.parti_vs_IA
Les scenes pour chaque fenetre.
Definition at line 63 of file Game.java.
Referenced by Acceuil.Acceuil(), Game(), mode_joueur_solo(), mode_joueur_vs_IA(), and mode_joueur_vs_joueur().
text_coup_restant
Text Game.text_coup_restant static
Variable de type 'Text' pour afficher le nombre de coup restant dans le mode solo.
Definition at line 79 of file Game.java.
Referenced by Game(), and mode_joueur_solo().
The documentation for this class was generated from the following file:
/Users/vijayakulanathanthanushan/Programmation/Java/Bataille navale/src/Game.java