Bataille Navale Java/JavaFX: Grille Class Reference
Grille Class Reference
Classe implémentant une grille complète à l'aide d'objets de type 'Case'.
Public Member Functions
Grille (int positionX, int positionY, boolean can_i_click)
Constructeur de la classe Grille : ce constructeur créé une grille en fonction de trois paramètres :
void score ()
Fonction qui affiche le score de la grille.
void test_win_or_loose ()
Fonction qui parcoure le contenu de la grille, et qui teste si la grille en question est gagnante ou perdante, si elle est gagnante on appelle la fonction 'print_win', si elle est perdante on appelle la fonction 'print_game_over'.
void print_win ()
Fonction servant à afficher l'image 'win.gif' à des coordonnées définies selon le mode de jeux.
void print_game_over ()
Fonction servant à afficher l'image 'game_over.png' à des coordonnées définies selon le mode de jeux.
Public Attributes
Case [][] cases
Tableau à deux dimensions de types 'Case', contenant toutes les cases de la grille.
int positionX
Position en absicce et en ordonnée de la grille sur la fenetre principale.
Text score = new Text()
variable de type 'Text' affichant le score
int nombre_bato_coulé
Variable servant à compter le nombre de bateau coulé pour savoir si l'on a gagné ou pas.
ImageView win_picture
Variable de type 'ImageView' initialisant les images 'win.gif' et 'game_over.png'.
boolean is_IA_grille
Variable définissant si la grille est faite pour l'IA ou non (ceci car l'on ne doit pas pouvoir cliquer sur la grille de l'IA)
Static Public Attributes
static int grilleH = 10
Nombre de case de la grille en longueur et en largeur.
Detailed Description
Classe implémentant une grille complète à l'aide d'objets de type 'Case'.
Definition at line 13 of file Grille.java.
Constructor & Destructor Documentation
Grille()
Grille.Grille (int positionX, int positionY, boolean can_i_click)
Constructeur de la classe Grille : ce constructeur créé une grille en fonction de trois paramètres :
La position en absicce (int positionX)
La position en ordonnée (int positionY)
La possibilitée ou non de pouvoir cliquer sur la grille (boolean can_i_click)
Definition at line 36 of file Grille.java.
References grilleH, positionX, and score().
{
         this.positionX = positionX;
         this.positionY = positionY;
         this.nombre_bato_coulé = 0;
         if(can_i_click == true)
             this.is_IA_grille = false;
         else
             this.is_IA_grille = true;
         GridPane plateau = new GridPane();
         plateau.setPadding(new Insets(positionY, 0, 0, positionX)); // hauteur , longueur
         plateau.setVgap(0);
         plateau.setHgap(0);
         this.cases = new Case[this.grilleW][this.grilleH];//Tableau de 10*10 cases
         for(int i = 0; i < this.grilleH; i++)
         {
                 for(int j=0; j < this.grilleW; j++)
                 {
                     this.cases[i][j] = new Case(can_i_click);//i=abs,j=ord,0=etat
                     plateau.add(this.cases[i][j], j, i); //inverser j et i car dans gridpane le remplissage se fait verticalement par defaut
                  }
         }
         score();
         this.getChildren().add(plateau);
    }
Member Function Documentation
print_game_over()
void Grille.print_game_over ()
Fonction servant à afficher l'image 'game_over.png' à des coordonnées définies selon le mode de jeux.
Definition at line 164 of file Grille.java.
References Game.mode_de_jeu.
Referenced by test_win_or_loose().
     {
         game_over_picture = new ImageView(new Image(getClass().getResource("images/game_over.png").toExternalForm()));
         if(Game.mode_de_jeu == Game.Mode.SOLO)
         {
             game_over_picture.setX(260);
             game_over_picture.setY(152);
         }
         else
         {
             game_over_picture.setX(366);
             game_over_picture.setY(159);
         }
         this.getChildren().add(game_over_picture);
     }
print_win()
void Grille.print_win ()
Fonction servant à afficher l'image 'win.gif' à des coordonnées définies selon le mode de jeux.
Definition at line 147 of file Grille.java.
References Game.mode_de_jeu, and win_picture.
Referenced by test_win_or_loose().
     {
         win_picture = new ImageView(new Image(getClass().getResource("images/win.gif").toExternalForm()));
         if(Game.mode_de_jeu == Game.Mode.SOLO)
         {
             win_picture.setX(260);
             win_picture.setY(152);
         }
         else
         {
             win_picture.setX(372);
             win_picture.setY(152);
         }
         this.getChildren().add(win_picture);
     }
score()
void Grille.score ()
Fonction qui affiche le score de la grille.
Cette fonction parcours l'intégralité de la grille, et stocke dans l'attribut (nombre_bato_coulé) le nombre de bateau qui a été coulé dans la grille afin de l'afficher par la suite.
Definition at line 71 of file Grille.java.
References cases, grilleH, and nombre_bato_coulé.
Referenced by Grille().
     {
        for(int i=0; i< this.grilleH; i++)
        {
            for(int j=0; j< this.grilleW ; j++)
            {
                if(this.cases[i][j].boat == true && this.cases[i][j].visited == true)
                    nombre_bato_coulé++;
            }
        }
         this.score.setFont(Font.font("Brushed script", FontWeight.BOLD, 22));
         this.score.setFill(Color.WHITE);
         this.score.setX(this.positionX  + 23);
         this.score.setY(this.positionY + (cases[0][0].forme.getHeight()*(grilleW+1)) + 15);
         this.score.setOpacity(0.8);
     this.score.setStroke(Color.BLACK);
         this.score.setText(+nombre_bato_coulé+" / 17 Bateau adverse détruit");
         try{
             this.getChildren().add(this.score);}
         catch(Exception e){};
         this.nombre_bato_coulé = 0;
     }
test_win_or_loose()
void Grille.test_win_or_loose ()
Fonction qui parcoure le contenu de la grille, et qui teste si la grille en question est gagnante ou perdante, si elle est gagnante on appelle la fonction 'print_win', si elle est perdante on appelle la fonction 'print_game_over'.
Definition at line 100 of file Grille.java.
References Game.coup_depart, Game.coup_restant, grilleH, Game.mode_de_jeu, print_game_over(), and print_win().
Referenced by Case.Case(), and IA.play().
     {
         int bato_trouvé = 0;
         int case_visitée = 0;
         //boucle qui va compter le nombre de bato coulé
         for(int i=0; i< this.grilleH; i++)
         {
            for(int j=0; j< this.grilleW ; j++)
            {
                if(this.cases[i][j].boat == true && this.cases[i][j].visited == true)
                    bato_trouvé++;
                if(this.cases[i][j].visited == true)
                    case_visitée++;
            }
         }
         //si on est en mode solo, on verifie le nombre de coup restant pour voir si on ne l'a pas dépasser ..
         if(Game.mode_de_jeu == Game.Mode.SOLO)
         {
             if(Game.coup_depart - Game.coup_restant == Game.coup_depart)
                 print_game_over();
         }
         //si on est en mode joueur contre IA si l'IA gagne alors on aura perdu, il faut donc inverses win et game_over
         if(Game.mode_de_jeu == Game.Mode.JOUEUR_VS_IA)
         {
             if(this.is_IA_grille == true) // si la grille en question apartient bien a l'IA
             {
                 if(bato_trouvé == 17)
                     print_game_over();
                 if(case_visitée == grilleH*grilleW)
                     print_win();
             }
             return;
         }
         //si le nombre de bato coulé trouvé est bien égal au total alors on a gagné ...
         if(bato_trouvé == 17)
             print_win();
         //si toute les cases du tableau sont remplie en premier, alors on a gagné
         if(case_visitée == grilleH*grilleW)
             print_win();
     }
Member Data Documentation
cases
Case [][] Grille.cases
Tableau à deux dimensions de types 'Case', contenant toutes les cases de la grille.
Definition at line 16 of file Grille.java.
Referenced by IA.continue_with_same_boat(), Game.mode_joueur_solo(), Game.mode_joueur_vs_IA(), Game.mode_joueur_vs_joueur(), IA.play(), IA.print_adversary_boat(), IA.random_shot(), Game.reset(), score(), and IA.shot_with_neighbor().
grilleH
int Grille.grilleH = 10 static
Nombre de case de la grille en longueur et en largeur.
Definition at line 20 of file Grille.java.
Referenced by IA.continue_with_same_boat(), Grille(), IA.print_adversary_boat(), IA.random_shot(), Game.reset(), score(), IA.shot_with_neighbor(), and test_win_or_loose().
is_IA_grille
boolean Grille.is_IA_grille
Variable définissant si la grille est faite pour l'IA ou non (ceci car l'on ne doit pas pouvoir cliquer sur la grille de l'IA)
Definition at line 28 of file Grille.java.
nombre_bato_coulé
int Grille.nombre_bato_coulé
Variable servant à compter le nombre de bateau coulé pour savoir si l'on a gagné ou pas.
Definition at line 24 of file Grille.java.
Referenced by score().
positionX
int Grille.positionX
Position en absicce et en ordonnée de la grille sur la fenetre principale.
Definition at line 18 of file Grille.java.
Referenced by Grille().
score
Text Grille.score = new Text()
variable de type 'Text' affichant le score
Definition at line 22 of file Grille.java.
Referenced by Case.Case(), IA.play(), and Game.reset().
win_picture
ImageView Grille.win_picture
Variable de type 'ImageView' initialisant les images 'win.gif' et 'game_over.png'.
Definition at line 26 of file Grille.java.
Referenced by print_win(), and Game.reset().
The documentation for this class was generated from the following file:
/Users/vijayakulanathanthanushan/Programmation/Java/Bataille navale/src/Grille.java